### This is the XXX subdirectory of the plague project

### Hooks for the editor to set the default target

current: target
-include target.mk

##################################################################

Makefile: makestuff
makestuff:
	/bin/ln -s ../../makestuff

-include makestuff/git.mk
-include makestuff/visual.mk

-include makestuff/wrapR.mk
-include makestuff/texdeps.mk

