library(methods)
library(emdbook)
library(epigrowthfit)
library(dplyr)
library(xtable)

args = commandArgs(trailingOnly=TRUE)
file = if (length(args) < 1) paste0(rtargetname, ".tex") else args[1]

rfun <- function(n) {
    gsub(".*\\.","",n)
}

ss <- (summary.fitList(fitList,level=2)
    %>% drop_bad()
)

## check bad fits.
## don't need gof>0 requirement
with(ss,table(source,cut(growthrate.value,c(-Inf,1,100,Inf)),gof>0))

bad_to_na <- function(x,lwr=-Inf,upr=Inf) {
    x[x<lwr | x>upr] <- NA
    return(x)
}

# filter out/NA-replace bad values
ss <- (ss
    %>% filter(gof>0,growthrate.value>1,growthrate.value<100,conv==0)
    %>% mutate_at(vars(starts_with("growthrate")),
                  funs(bad_to_na(.,0.1,200)))
    %>% mutate_at(vars(starts_with("doubling")),
                  funs(bad_to_na(.,1,1000)))
)

conv <- function(colname) {
    ss %>% select(source,outbreak.year,starts_with(colname)) %>%
        rename_at(vars(starts_with(colname)),rfun) %>%
        rename(epidemic="outbreak.year") %>%
        arrange(epidemic,source)
}

growth.rate <- conv("growthrate")
doubling.time <- conv("doublingtime")
gof <- conv("gof") %>% rename(value="gof") %>% mutate(lower=NA,upper=NA)
R0 <- conv("R0")
final.size <- conv("finalsize")

data <- list(growth.rate = growth.rate,
             doubling.time = doubling.time,
             goodness.of.fit = gof)

latexTable(
  data, 
  columns = c("growth.rate", "doubling.time", "goodness.of.fit"),
  colnames = c("Growth rate [$1/\\text{year}]$", "Doubling time [days]",
               "\\ \\ $R^2$"),
  comment = "generated by analysis/tables/minorparams.R",
  digits = c(1,1,3), # 3 for gof
  file = file)
