library(methods)
library(emdbook)
library(epigrowthfit)
library(dplyr)
library(xtable)

args = commandArgs(trailingOnly=TRUE)
file = if (length(args) < 1) paste0(rtargetname, ".tex") else args[1]

rfun <- function(n) {
    gsub(".*\\.","",n)
}
## testing
## summary(fitList[[1]][[1]],plague_R0=TRUE)
## trace("summary",sig="epigrowthfit", browser)
## debug(epigrowthfit:::summary.epigrowthfit)
ss <- (summary.fitList(fitList,level=2,plague_R0=TRUE)
    %>% drop_bad()
    %>% select(source,outbreak.year,
           ends_with("value"),
           ends_with("lower"),
           ends_with("upper"),
           "gof")
)
          
ss2 <- (preds
    %>% as_tibble()
    %>% mutate(outbreak.year=as.character(epoch),
               source=
              case_when(source=="wills" & epoch=="early" ~ "Husting wills",
                        source=="wills" & epoch=="late" ~ "Canterbury wills",
                        source=="LBoM"  ~ "London bills",
                        source=="parish" ~ "London parish"))
    %>% select(-epoch)
    %>% bind_rows(ss)
    %>% mutate(outbreak.year = factor(outbreak.year,
             levels=c(sort(unique(outbreak.year[substr(outbreak.year,1,1)=="1"])),
                      "early","late")))
)

conv <- function(colname) {
    ss2 %>% select(source,outbreak.year,starts_with(colname)) %>%
        rename_at(vars(starts_with(colname)),rfun) %>%
        rename(epidemic="outbreak.year") %>%
        arrange(epidemic,source)
}

growth.rate <- conv("growthrate") %>%
    mutate(value=round(value,1), lower=round(lower,1), upper=round(upper,1))
doubling.time <- conv("doublingtime") %>%
    mutate(value=round(value,1), lower=round(lower,1), upper=round(upper,1))
gof <- conv("gof") %>% rename(value="gof") %>% mutate(lower=NA,upper=NA)
R0 <- conv("R0")
final.size <- conv("finalsize")

data <- list(growth.rate = growth.rate,
             doubling.time = doubling.time,
             R0 = R0,
             final.size = final.size,
             goodness.of.fit = gof)

## source("table.R")

## latexTable(
##   data, 
##   columns = c("growth.rate", "doubling.time", "R0", "final.size", "goodness.of.fit"),
##   colnames = c("Growth rate [$1/\\text{year}]$", "Doubling time [days]", "Implied pneumonic plague basic reproduction number $\\rzerop$", "Implied pneumonic plague attack rate $\\Zp$", "\\ \\ $R^2$"),
##   comment = "generated by analysis/tables/params.R",
##   digits = c(1,1,2,2,3), # two decimals for R0, final.size; 3 for gof
##   file = file)

to_string <- function(x,digits) {
    with(x, {
        format <- paste0(
            ifelse(x$value < 10, "\\ \\,", ""),
            "%.", digits, "f (%.", digits, "f,%.", digits, "f)")
        ss <- sprintf(format, value, lower, upper)
        return(ss)
    })
}

dd <- with(data,
  data.frame(source=growth.rate$source, epidemic=growth.rate$epidemic,
             r=to_string(data$growth.rate,1),
             t=to_string(data$doubling.time,1),
             R0=to_string(data$R0,2),
             final.size=to_string(data$final.size,2),
             goodness.of.fit=round(data$goodness.of.fit$value,3)
             )
  )

ltx <- Hmisc::latex(dd,
      multicol=TRUE, # allow \multicolumn in header
      rowname=NULL,
      cgroup=c("", "Assuming pneumonic plague",""),
      n.cgroup=c(4,2,1),
      colheads=c("Source","Epidemic", "$\\text{Growth rate}\\atop[1/\\text{year}]$", "$\\text{Doubling time}\\atop[\\text{days}]$", "$\\rzerop$", "Attack rate $\\Zp$", "\\ \\ $R^2$"),
      col.just = c("l","c",rep("l",5)),
      table.env=FALSE,
      file=file
      )
